package org.jhipster.biblioteca.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GeneroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneroAllPropertiesEquals(Genero expected, Genero actual) {
        assertGeneroAutoGeneratedPropertiesEquals(expected, actual);
        assertGeneroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneroAllUpdatablePropertiesEquals(Genero expected, Genero actual) {
        assertGeneroUpdatableFieldsEquals(expected, actual);
        assertGeneroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneroAutoGeneratedPropertiesEquals(Genero expected, Genero actual) {
        assertThat(expected)
            .as("Verify Genero auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneroUpdatableFieldsEquals(Genero expected, Genero actual) {
        assertThat(expected)
            .as("Verify Genero relevant properties")
            .satisfies(e -> assertThat(e.getGenero()).as("check genero").isEqualTo(actual.getGenero()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneroUpdatableRelationshipsEquals(Genero expected, Genero actual) {
        // empty method
    }
}
